-- 0001_initial.sql — StockPanic India initial schema
-- Design and rationale: docs/database/schema.md, docs/database/partitioning.md
-- Target: PostgreSQL 17+. Run as the database owner (superuser on the self-managed host, ADR-003):
-- the event trigger in §1 requires superuser.

BEGIN;
SET LOCAL timezone TO 'UTC';

CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version    text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- §1  GUARDRAILS §4.3 / D-014 — no AI tone or sentiment storage, ever.
-- Any table, view or column whose name contains the word "tone" or
-- "sentiment" (as a whole underscore-delimited word) is rejected at DDL time.
-- =====================================================================

CREATE FUNCTION forbid_tone_columns() RETURNS event_trigger
LANGUAGE plpgsql AS $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT c.relname, a.attname
    FROM pg_event_trigger_ddl_commands() cmd
    JOIN pg_class c ON c.oid = cmd.objid
    LEFT JOIN pg_attribute a
      ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
    WHERE cmd.classid = 'pg_class'::regclass
      AND (c.relname ~* '(^|_)(tone|sentiment)(_|$)'
           OR a.attname ~* '(^|_)(tone|sentiment)(_|$)')
  LOOP
    RAISE EXCEPTION 'GUARDRAILS 4.3 / D-014: %.% would store AI tone or sentiment',
      r.relname, coalesce(r.attname, '*');
  END LOOP;
END $$;

CREATE EVENT TRIGGER no_tone_columns ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'ALTER TABLE', 'CREATE TABLE AS',
               'CREATE VIEW', 'CREATE MATERIALIZED VIEW')
  EXECUTE FUNCTION forbid_tone_columns();

-- =====================================================================
-- §2  Types and domains
-- =====================================================================

CREATE DOMAIN exchange_code AS text CHECK (VALUE IN ('NSE', 'BSE'));
CREATE DOMAIN isin_code     AS char(12) CHECK (VALUE ~ '^IN[A-Z0-9]{9}[0-9]$');
CREATE DOMAIN username      AS citext CHECK (VALUE ~ '^[A-Za-z0-9_]{3,20}$');

CREATE TYPE instrument_segment   AS ENUM ('mainboard', 'sme');
CREATE TYPE instrument_status    AS ENUM ('listed', 'suspended', 'delisted', 'merged');
CREATE TYPE session_type         AS ENUM ('pre_open', 'open', 'closed', 'holiday', 'special', 'halted');
CREATE TYPE source_kind          AS ENUM ('filing', 'article', 'regulator');
CREATE TYPE health_state         AS ENUM ('healthy', 'stale', 'down');
CREATE TYPE item_kind            AS ENUM ('filing', 'article');
CREATE TYPE item_status          AS ENUM ('live', 'removed_by_source', 'withdrawn_by_exchange');
CREATE TYPE tag_method           AS ENUM ('exchange_code', 'model', 'operator');
CREATE TYPE classification_source AS ENUM ('rule', 'model', 'operator');
CREATE TYPE summary_status       AS ENUM ('shown', 'hidden_by_operator');
CREATE TYPE ai_job               AS ENUM ('classify', 'summarise');
CREATE TYPE user_role            AS ENUM ('user', 'operator', 'admin');
CREATE TYPE vote_direction       AS ENUM ('bullish', 'bearish', 'neutral');
CREATE TYPE quality_vote         AS ENUM ('important', 'duplicate', 'wrong_stock', 'spam', 'old_news');
CREATE TYPE comment_state        AS ENUM ('visible', 'deleted_by_author', 'removed');
CREATE TYPE report_reason        AS ENUM ('defamation', 'impersonation', 'obscene', 'threat', 'hate_speech',
                                          'privacy', 'copyright', 'spam', 'other_unlawful');
CREATE TYPE removal_reason       AS ENUM ('defamation', 'impersonation', 'obscene', 'threat', 'hate_speech',
                                          'privacy', 'copyright', 'spam', 'other_unlawful',
                                          'court_order', 'government_notice');
CREATE TYPE alert_kind           AS ENUM ('alert', 'correction');
CREATE TYPE alert_via            AS ENUM ('individual', 'digest');
CREATE TYPE plan_id              AS ENUM ('monthly', 'yearly');
CREATE TYPE subscription_status  AS ENUM ('active', 'past_due', 'cancelled', 'expired');
CREATE TYPE tier                 AS ENUM ('free', 'paid');
CREATE TYPE actor_type           AS ENUM ('user', 'operator', 'system');
CREATE TYPE grievance_source     AS ENUM ('report', 'form', 'court_order', 'government_notice');
CREATE TYPE grievance_status     AS ENUM ('open', 'acknowledged', 'resolved', 'rejected');
CREATE TYPE stream_view          AS ENUM ('latest', 'watchlist', 'important', 'bullish', 'bearish', 'trending');

-- Public IDs are ULIDs generated by the application, with a type prefix.
CREATE FUNCTION is_public_id(p_value text, p_prefix text) RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
  SELECT p_value ~ ('^' || p_prefix || '_[0-9A-HJKMNP-TV-Z]{26}$')
$$;

-- =====================================================================
-- §3  Settings (kill switches, thresholds, model config)
-- =====================================================================

CREATE TABLE setting (
  key        text PRIMARY KEY CHECK (key ~ '^[a-z][a-z0-9_]*$'),
  value      jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint
);

-- =====================================================================
-- §4  Instrument registry — ADR-001, GUARDRAILS §4.1/§4.2
-- ISIN is the only instrument identity. Every symbol, code, name, alias
-- and group link carries a validity period; overlaps are impossible.
-- =====================================================================

CREATE TABLE instrument (
  isin           isin_code PRIMARY KEY,
  segment        instrument_segment NOT NULL,
  status         instrument_status NOT NULL DEFAULT 'listed',
  listed_on      date,
  successor_isin isin_code REFERENCES instrument (isin),
  created_at     timestamptz NOT NULL DEFAULT now(),
  CHECK (successor_isin IS NULL OR successor_isin <> isin),
  CHECK (status <> 'merged' OR successor_isin IS NOT NULL)
);

CREATE TABLE instrument_code (
  id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  isin     isin_code NOT NULL REFERENCES instrument (isin),
  exchange exchange_code NOT NULL,
  code     text NOT NULL CHECK (code <> ''),
  valid    daterange NOT NULL CHECK (NOT isempty(valid) AND NOT lower_inf(valid)),
  -- one code means one instrument at any moment, per exchange
  EXCLUDE USING gist (exchange WITH =, code WITH =, valid WITH &&),
  -- one instrument has one code per exchange at any moment
  EXCLUDE USING gist (isin WITH =, exchange WITH =, valid WITH &&)
);
CREATE INDEX instrument_code_trgm ON instrument_code USING gin (code gin_trgm_ops);

CREATE TABLE instrument_name (
  id    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  isin  isin_code NOT NULL REFERENCES instrument (isin),
  kind  text NOT NULL CHECK (kind IN ('legal', 'short')),
  name  text NOT NULL CHECK (name <> ''),
  valid daterange NOT NULL CHECK (NOT isempty(valid) AND NOT lower_inf(valid)),
  EXCLUDE USING gist (isin WITH =, kind WITH =, valid WITH &&)
);
CREATE INDEX instrument_name_trgm ON instrument_name USING gin (lower(name) gin_trgm_ops);

CREATE TABLE instrument_alias (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  isin        isin_code NOT NULL REFERENCES instrument (isin),
  alias       text NOT NULL CHECK (alias <> ''),
  alias_norm  text NOT NULL CHECK (alias_norm <> ''),
  kind        text NOT NULL CHECK (kind IN ('generated', 'curated', 'operator')),
  ambiguous   boolean NOT NULL DEFAULT false,
  common_word boolean NOT NULL DEFAULT false,
  valid       daterange NOT NULL CHECK (NOT isempty(valid) AND NOT lower_inf(valid)),
  EXCLUDE USING gist (isin WITH =, alias_norm WITH =, valid WITH &&)
);
CREATE INDEX instrument_alias_trgm ON instrument_alias USING gin (alias_norm gin_trgm_ops);

-- Group links are for display only; never used to add tags (entity-resolution.md §4.1).
CREATE TABLE instrument_group_link (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  isin       isin_code NOT NULL REFERENCES instrument (isin),
  group_name text NOT NULL CHECK (group_name <> ''),
  relation   text NOT NULL CHECK (relation IN ('parent', 'promoter_group')),
  valid      daterange NOT NULL CHECK (NOT isempty(valid) AND NOT lower_inf(valid)),
  EXCLUDE USING gist (isin WITH =, group_name WITH =, relation WITH =, valid WITH &&)
);

-- Market sessions — GUARDRAILS §4.11; system overview M1/M2.
CREATE TABLE trading_session (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  exchange_date date NOT NULL,
  session       session_type NOT NULL,
  starts_at     timestamptz NOT NULL,
  ends_at       timestamptz NOT NULL,
  CHECK (ends_at > starts_at),
  EXCLUDE USING gist (tstzrange(starts_at, ends_at) WITH &&)
);

-- =====================================================================
-- §5  Sources and items — PRD-002 §2–3, ingestion.md
-- =====================================================================

CREATE TABLE source (
  source_id         text PRIMARY KEY CHECK (source_id ~ '^src_[a-z0-9_]+$'),
  name              text NOT NULL CHECK (name <> ''),
  kind              source_kind NOT NULL,
  tier              smallint NOT NULL CHECK (tier BETWEEN 1 AND 4),
  access_basis      text,
  access_checked_on date,
  excerpt_allowed   boolean NOT NULL DEFAULT false,
  enabled           boolean NOT NULL DEFAULT false,
  cadence           jsonb NOT NULL,
  -- PRD-002 US-002.5 AC-1/AC-7: no access basis, no ingestion
  CHECK (NOT enabled OR (coalesce(access_basis, '') <> '' AND access_checked_on IS NOT NULL)),
  CHECK (kind <> 'filing' OR tier = 1)
);

CREATE TABLE source_health (
  source_id            text PRIMARY KEY REFERENCES source (source_id),
  state                health_state NOT NULL DEFAULT 'healthy',
  last_attempt_at      timestamptz,
  last_success_at      timestamptz,
  consecutive_failures integer NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
  last_error           text,
  changed_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE raw_inbox (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  source_id    text NOT NULL REFERENCES source (source_id),
  received_at  timestamptz NOT NULL DEFAULT now(),
  payload      jsonb NOT NULL,
  processed_at timestamptz
);
CREATE INDEX raw_inbox_unprocessed ON raw_inbox (received_at) WHERE processed_at IS NULL;

CREATE TABLE item (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id     text NOT NULL UNIQUE CHECK (is_public_id(public_id, 'it')),
  kind          item_kind NOT NULL,
  source_id     text NOT NULL REFERENCES source (source_id),
  dedup_key     text NOT NULL CHECK (dedup_key <> ''),
  headline      text NOT NULL CHECK (headline <> ''),
  url           text NOT NULL CHECK (url ~ '^https?://'),
  published_at  timestamptz,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  language      text NOT NULL DEFAULT 'en' CHECK (language = 'en'),   -- Product Definition N14
  excerpt       text,
  status        item_status NOT NULL DEFAULT 'live',
  UNIQUE (source_id, dedup_key),                                      -- ingestion.md §3 rule 1
  CHECK (status <> 'withdrawn_by_exchange' OR kind = 'filing')
);

-- PRD-002 C-002.8: an excerpt only where the source's access basis allows it.
CREATE FUNCTION item_excerpt_allowed() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.excerpt IS NOT NULL AND NOT (SELECT excerpt_allowed FROM source WHERE source_id = NEW.source_id) THEN
    RAISE EXCEPTION 'PRD-002 C-002.8: source % does not permit excerpts', NEW.source_id;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER item_excerpt_allowed BEFORE INSERT OR UPDATE OF excerpt, source_id ON item
  FOR EACH ROW EXECUTE FUNCTION item_excerpt_allowed();

CREATE TABLE filing_detail (
  item_id         bigint PRIMARY KEY REFERENCES item (id),
  exchange        exchange_code NOT NULL,
  announcement_id text NOT NULL CHECK (announcement_id <> ''),
  scrip_code      text NOT NULL CHECK (scrip_code <> ''),
  category        text,
  attachment_url  text CHECK (attachment_url ~ '^https?://'),
  extracted_text  text,
  UNIQUE (exchange, announcement_id)
);

CREATE TABLE item_revision (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_id    bigint NOT NULL REFERENCES item (id),
  revised_at timestamptz NOT NULL DEFAULT now(),
  previous   jsonb NOT NULL
);
CREATE INDEX item_revision_item ON item_revision (item_id);

CREATE TABLE reconciliation_run (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  exchange           exchange_code NOT NULL,
  for_date           date NOT NULL,
  run_at             timestamptz NOT NULL DEFAULT now(),
  expected           integer NOT NULL CHECK (expected >= 0),
  ingested           integer NOT NULL CHECK (ingested >= 0),
  backfilled         integer NOT NULL DEFAULT 0 CHECK (backfilled >= 0),
  coverage           numeric(6,5) GENERATED ALWAYS AS
                       (CASE WHEN expected = 0 THEN 1 ELSE least(ingested::numeric / expected, 1) END) STORED
);
CREATE INDEX reconciliation_run_date ON reconciliation_run (for_date DESC, exchange);

-- =====================================================================
-- §6  Stories — PRD-002 §4, deduplication.md
-- =====================================================================

CREATE TABLE story (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id       text NOT NULL UNIQUE CHECK (is_public_id(public_id, 'st')),
  first_seen_at   timestamptz NOT NULL,
  updated_at      timestamptz NOT NULL DEFAULT now(),
  primary_item_id bigint,
  source_count    integer NOT NULL DEFAULT 1 CHECK (source_count >= 1),
  merged_into     bigint REFERENCES story (id),
  CHECK (merged_into IS NULL OR merged_into <> id),
  -- a live story always has a primary item; an absorbed (merged) story has none
  CHECK ((merged_into IS NULL) = (primary_item_id IS NOT NULL))
);
CREATE INDEX story_stream ON story (first_seen_at DESC, id DESC) WHERE merged_into IS NULL;

-- An item belongs to exactly one story (PK on item_id).
CREATE TABLE story_item (
  item_id   bigint PRIMARY KEY REFERENCES item (id),
  story_id  bigint NOT NULL REFERENCES story (id),
  joined_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (story_id, item_id)
);

-- The primary item must be one of the story's own items.
ALTER TABLE story
  ADD CONSTRAINT story_primary_item_in_story
  FOREIGN KEY (id, primary_item_id) REFERENCES story_item (story_id, item_id)
  DEFERRABLE INITIALLY DEFERRED;

-- PRD-001 US-001.1 AC-4: rows never move; identities never change.
CREATE FUNCTION story_immutable_fields() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.first_seen_at IS DISTINCT FROM OLD.first_seen_at THEN
    RAISE EXCEPTION 'PRD-001 US-001.1 AC-4: story.first_seen_at is immutable';
  END IF;
  IF NEW.public_id IS DISTINCT FROM OLD.public_id THEN
    RAISE EXCEPTION 'story.public_id is immutable';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER story_immutable_fields BEFORE UPDATE ON story
  FOR EACH ROW EXECUTE FUNCTION story_immutable_fields();

-- Denormalised story time, copied from story (immutable), for index-ordered scans.
CREATE FUNCTION copy_story_first_seen() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  SELECT first_seen_at INTO NEW.story_first_seen_at FROM story WHERE id = NEW.story_id;
  RETURN NEW;
END $$;

CREATE TABLE story_tag (
  story_id            bigint NOT NULL REFERENCES story (id),
  isin                isin_code NOT NULL REFERENCES instrument (isin),
  method              tag_method NOT NULL,
  confidence          numeric(4,3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  calibration_version text,
  story_first_seen_at timestamptz NOT NULL,
  PRIMARY KEY (story_id, isin),
  CHECK (method = 'model' OR confidence = 1),
  CHECK (method <> 'model' OR calibration_version IS NOT NULL)
);
CREATE INDEX story_tag_isin_time ON story_tag (isin, story_first_seen_at DESC, story_id DESC);
CREATE TRIGGER story_tag_copy_time BEFORE INSERT OR UPDATE OF story_id ON story_tag
  FOR EACH ROW EXECUTE FUNCTION copy_story_first_seen();

CREATE TABLE story_unresolved_mention (
  story_id bigint NOT NULL REFERENCES story (id),
  mention  text NOT NULL CHECK (mention <> ''),
  PRIMARY KEY (story_id, mention)
);

CREATE TABLE lsh_band (
  band_hash  bigint NOT NULL,
  story_id   bigint NOT NULL REFERENCES story (id),
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (band_hash, story_id)
);
CREATE INDEX lsh_band_expiry ON lsh_band (expires_at);

-- =====================================================================
-- §7  Event types — PRD-004 §1
-- =====================================================================

CREATE TABLE event_type (
  code             text PRIMARY KEY CHECK (code ~ '^[a-z][a-z_]*$'),
  label            text NOT NULL,
  alert_default    boolean NOT NULL,
  taxonomy_version integer NOT NULL CHECK (taxonomy_version >= 1),
  retired_to       text REFERENCES event_type (code),
  CHECK (retired_to IS NULL OR retired_to <> code)
);

CREATE TABLE story_event_type (
  story_id            bigint NOT NULL REFERENCES story (id),
  code                text NOT NULL REFERENCES event_type (code),
  source              classification_source NOT NULL,
  story_first_seen_at timestamptz NOT NULL,
  PRIMARY KEY (story_id, code)
);
CREATE INDEX story_event_type_code_time ON story_event_type (code, story_first_seen_at DESC, story_id DESC);
CREATE TRIGGER story_event_type_copy_time BEFORE INSERT OR UPDATE OF story_id ON story_event_type
  FOR EACH ROW EXECUTE FUNCTION copy_story_first_seen();

-- PRD-004 US-004.1 AC-1: a live story always has at least one event type.
CREATE FUNCTION assert_story_has_event_type(p_story bigint) RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM story WHERE id = p_story AND merged_into IS NULL)
     AND NOT EXISTS (SELECT 1 FROM story_event_type WHERE story_id = p_story) THEN
    RAISE EXCEPTION 'PRD-004 US-004.1 AC-1: story % has no event type', p_story;
  END IF;
END $$;

CREATE FUNCTION story_inserted_check_event_type() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM assert_story_has_event_type(NEW.id);
  RETURN NULL;
END $$;

CREATE FUNCTION event_type_removed_check_story() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM assert_story_has_event_type(OLD.story_id);
  RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER story_requires_event_type
  AFTER INSERT ON story DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION story_inserted_check_event_type();
CREATE CONSTRAINT TRIGGER story_keeps_event_type
  AFTER DELETE OR UPDATE OF story_id ON story_event_type DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION event_type_removed_check_story();

-- =====================================================================
-- §8  AI — PRD-004 §5, ai-layer.md, D-025
-- =====================================================================

-- Summaries reference a filing: summaries of articles are unrepresentable (PRD-004 US-004.4 AC-1).
CREATE TABLE story_summary (
  story_id       bigint PRIMARY KEY REFERENCES story (id),
  source_item_id bigint NOT NULL REFERENCES filing_detail (item_id),
  body           text NOT NULL CHECK (body <> ''),
  word_count     integer GENERATED ALWAYS AS (cardinality(regexp_split_to_array(btrim(body), '\s+'))) STORED,
  citations      jsonb NOT NULL,
  checks         jsonb NOT NULL,
  status         summary_status NOT NULL DEFAULT 'shown',
  model_id       text NOT NULL,
  prompt_version text NOT NULL,
  ai_call_id     bigint NOT NULL,
  generated_at   timestamptz NOT NULL DEFAULT now(),
  CHECK (word_count <= 100)                                     -- PRD-004 US-004.4 AC-2 (founder)
);

CREATE TABLE ai_call (
  id                bigint GENERATED ALWAYS AS IDENTITY,
  called_at         timestamptz NOT NULL DEFAULT now(),
  job               ai_job NOT NULL,
  item_id           bigint,
  story_id          bigint,
  model_id          text NOT NULL,
  prompt_version    text NOT NULL,
  input_hash        text NOT NULL,
  output            jsonb,
  checks            jsonb,
  outcome           text NOT NULL CHECK (outcome IN ('accepted', 'withheld', 'invalid', 'refused', 'error', 'timeout')),
  input_tokens      integer NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens     integer NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  cache_read_tokens integer NOT NULL DEFAULT 0 CHECK (cache_read_tokens >= 0),
  cost_inr          numeric(12,4) NOT NULL DEFAULT 0 CHECK (cost_inr >= 0),
  latency_ms        integer CHECK (latency_ms >= 0),
  PRIMARY KEY (id, called_at)
) PARTITION BY RANGE (called_at);

-- =====================================================================
-- §9  Users, auth, billing — PRD-007
-- =====================================================================

CREATE TABLE reserved_username (
  name citext PRIMARY KEY
);

CREATE TABLE app_user (
  id                    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id             text NOT NULL UNIQUE CHECK (is_public_id(public_id, 'us')),
  username              username UNIQUE,
  email                 citext UNIQUE,
  email_verified_at     timestamptz,
  google_sub            text UNIQUE,
  role                  user_role NOT NULL DEFAULT 'user',
  totp_enabled          boolean NOT NULL DEFAULT false,
  age_confirmed_at      timestamptz NOT NULL,                  -- PRD-007 C-007.6
  terms_accepted_at     timestamptz NOT NULL,
  privacy_consent_at    timestamptz NOT NULL,                  -- PRD-007 US-007.4 AC-2
  marketing_opt_in      boolean NOT NULL DEFAULT false,        -- PRD-007 US-007.4 AC-5
  created_at            timestamptz NOT NULL DEFAULT now(),
  username_changed_at   timestamptz,
  voting_revoked_at     timestamptz,
  comment_suspended_at  timestamptz,
  replies_seen_at       timestamptz,
  deletion_requested_at timestamptz,
  deleted_at            timestamptz,
  CHECK (role = 'user' OR totp_enabled),                       -- PRD-007 US-007.5 AC-2
  CHECK (deleted_at IS NOT NULL OR (email IS NOT NULL AND username IS NOT NULL)),
  CHECK (deleted_at IS NULL OR (email IS NULL AND google_sub IS NULL AND username IS NULL))
);

CREATE TABLE username_hold (
  username   citext PRIMARY KEY,
  user_id    bigint NOT NULL REFERENCES app_user (id),
  held_until timestamptz NOT NULL
);

-- PRD-007 US-007.2: reserved names, current NSE symbols, and held names are unavailable.
CREATE FUNCTION username_available() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.username IS NULL THEN RETURN NEW; END IF;
  IF EXISTS (SELECT 1 FROM reserved_username WHERE name = NEW.username) THEN
    RAISE EXCEPTION 'username_reserved: %', NEW.username;
  END IF;
  IF EXISTS (SELECT 1 FROM instrument_code
             WHERE exchange = 'NSE' AND upper(code) = upper(NEW.username::text)
               AND valid @> current_date) THEN
    RAISE EXCEPTION 'username_reserved: % is an NSE symbol', NEW.username;
  END IF;
  IF EXISTS (SELECT 1 FROM username_hold
             WHERE username = NEW.username AND held_until > now() AND user_id <> NEW.id) THEN
    RAISE EXCEPTION 'username_reserved: % is held', NEW.username;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER app_user_username_available BEFORE INSERT OR UPDATE OF username ON app_user
  FOR EACH ROW EXECUTE FUNCTION username_available();

CREATE TABLE user_session (
  token_hash   text PRIMARY KEY,
  user_id      bigint NOT NULL REFERENCES app_user (id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  revoked_at   timestamptz
);
CREATE INDEX user_session_user ON user_session (user_id) WHERE revoked_at IS NULL;

CREATE TABLE email_code (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email      citext NOT NULL,
  code_hash  text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  attempts   smallint NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),   -- PRD-007 US-007.1 AC-3
  used_at    timestamptz,
  CHECK (expires_at > created_at)
);
CREATE INDEX email_code_lookup ON email_code (email, created_at DESC) WHERE used_at IS NULL;

CREATE TABLE plan_entitlement (
  tier                 tier PRIMARY KEY,
  watchlist_limit      integer NOT NULL CHECK (watchlist_limit > 0),
  alert_budget_ceiling integer NOT NULL CHECK (alert_budget_ceiling >= 0),
  default_alert_budget integer NOT NULL CHECK (default_alert_budget >= 0),
  history_days         integer CHECK (history_days > 0),      -- NULL = all history
  alert_history_days   integer NOT NULL CHECK (alert_history_days > 0),
  multi_event_filter   boolean NOT NULL,
  stream_filings_only  boolean NOT NULL,
  saved_views          integer NOT NULL CHECK (saved_views >= 0),
  CHECK (default_alert_budget <= alert_budget_ceiling)
);

-- One trial per account, by construction (PRD-007 US-007.7 AC-2).
CREATE TABLE trial (
  user_id    bigint PRIMARY KEY REFERENCES app_user (id),
  started_at timestamptz NOT NULL DEFAULT now(),
  ends_at    timestamptz NOT NULL,
  CHECK (ends_at > started_at)
);

CREATE TABLE subscription (
  id                   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id              bigint NOT NULL REFERENCES app_user (id),
  plan                 plan_id NOT NULL,
  status               subscription_status NOT NULL,
  provider_ref         text NOT NULL UNIQUE,
  current_period_end   timestamptz NOT NULL,
  cancel_at_period_end boolean NOT NULL DEFAULT false,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX subscription_one_live ON subscription (user_id) WHERE status IN ('active', 'past_due');

CREATE TABLE invoice (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id         bigint NOT NULL REFERENCES app_user (id),
  subscription_id bigint REFERENCES subscription (id),
  amount_inr      numeric(10,2) NOT NULL CHECK (amount_inr >= 0),
  gst_inr         numeric(10,2) NOT NULL CHECK (gst_inr >= 0 AND gst_inr <= amount_inr),
  issued_at       timestamptz NOT NULL DEFAULT now(),
  provider_ref    text NOT NULL UNIQUE,
  pdf_url         text
);
CREATE INDEX invoice_user ON invoice (user_id, issued_at DESC);

-- =====================================================================
-- §10  Watchlist, unread, saved views, alerts — PRD-001, PRD-003
-- =====================================================================

CREATE TABLE watchlist_entry (
  user_id        bigint NOT NULL REFERENCES app_user (id),
  isin           isin_code NOT NULL REFERENCES instrument (isin),
  added_at       timestamptz NOT NULL DEFAULT now(),
  alerts_enabled boolean NOT NULL DEFAULT true,
  PRIMARY KEY (user_id, isin)
);
CREATE INDEX watchlist_alert_targets ON watchlist_entry (isin) INCLUDE (user_id) WHERE alerts_enabled;

CREATE TABLE stream_seen (
  user_id      bigint NOT NULL REFERENCES app_user (id),
  view         stream_view NOT NULL,
  last_seen_at timestamptz NOT NULL,
  PRIMARY KEY (user_id, view)
);
-- PRD-001 §4.3: last_seen_at never moves backwards.
CREATE FUNCTION stream_seen_monotonic() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.last_seen_at := greatest(OLD.last_seen_at, NEW.last_seen_at);
  RETURN NEW;
END $$;
CREATE TRIGGER stream_seen_monotonic BEFORE UPDATE ON stream_seen
  FOR EACH ROW EXECUTE FUNCTION stream_seen_monotonic();

CREATE TABLE saved_view (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    bigint NOT NULL REFERENCES app_user (id),
  name       text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 60),
  params     jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, name)
);

CREATE TABLE alert_settings (
  user_id       bigint PRIMARY KEY REFERENCES app_user (id),
  email_enabled boolean NOT NULL DEFAULT true,
  push_enabled  boolean NOT NULL DEFAULT false,
  daily_budget  integer NOT NULL CHECK (daily_budget BETWEEN 0 AND 30),
  quiet_enabled boolean NOT NULL DEFAULT true,
  quiet_start   time NOT NULL DEFAULT '22:00',
  quiet_end     time NOT NULL DEFAULT '08:00',
  digest_time   time NOT NULL DEFAULT '08:00',
  digest_only   boolean NOT NULL DEFAULT false,
  email_bounces integer NOT NULL DEFAULT 0 CHECK (email_bounces >= 0)
);

CREATE TABLE alert_event_type_pref (
  user_id bigint NOT NULL REFERENCES app_user (id),
  code    text NOT NULL REFERENCES event_type (code),
  enabled boolean NOT NULL,
  PRIMARY KEY (user_id, code)
);

CREATE TABLE push_subscription (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    bigint NOT NULL REFERENCES app_user (id),
  endpoint   text NOT NULL UNIQUE CHECK (endpoint ~ '^https://'),
  keys       jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE alert (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id         text NOT NULL UNIQUE CHECK (is_public_id(public_id, 'al')),
  user_id           bigint NOT NULL REFERENCES app_user (id),
  story_id          bigint NOT NULL REFERENCES story (id),
  kind              alert_kind NOT NULL,
  via               alert_via NOT NULL,
  channels          text[] NOT NULL CHECK (channels <@ ARRAY['email', 'push']::text[]),
  created_at        timestamptz NOT NULL DEFAULT now(),
  sent_at           timestamptz,
  corrected_at      timestamptz,
  corrects_alert_id bigint REFERENCES alert (id),
  removed_isin      isin_code,
  CHECK ((kind = 'correction') = (corrects_alert_id IS NOT NULL)),
  CHECK (kind = 'alert' OR removed_isin IS NOT NULL)
);
-- PRD-003 US-003.5 AC-4 / NFR-003.6: one alert per story per user, ever — by constraint.
CREATE UNIQUE INDEX alert_once_per_story ON alert (user_id, story_id) WHERE kind = 'alert';
CREATE INDEX alert_history ON alert (user_id, created_at DESC);

CREATE TABLE alert_budget_usage (
  user_id bigint NOT NULL REFERENCES app_user (id),
  day     date NOT NULL,                                       -- IST calendar day
  used    integer NOT NULL DEFAULT 0 CHECK (used >= 0),
  PRIMARY KEY (user_id, day)
);

CREATE TABLE digest (
  id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id  bigint NOT NULL REFERENCES app_user (id),
  for_date date NOT NULL,
  sent_at  timestamptz,
  UNIQUE (user_id, for_date)
);

CREATE TABLE digest_item (
  digest_id bigint NOT NULL REFERENCES digest (id),
  story_id  bigint NOT NULL REFERENCES story (id),
  PRIMARY KEY (digest_id, story_id)
);

-- =====================================================================
-- §11  Votes — PRD-005, D-011, D-021
-- =====================================================================

-- PRD-005 C-005.8: one directional vote per user per story, by primary key.
CREATE TABLE vote_directional (
  story_id      bigint NOT NULL REFERENCES story (id),
  user_id       bigint NOT NULL REFERENCES app_user (id),
  direction     vote_direction NOT NULL,
  cast_at       timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  discounted_at timestamptz,
  PRIMARY KEY (story_id, user_id)
);
CREATE INDEX vote_directional_recent ON vote_directional (cast_at DESC);
CREATE INDEX vote_directional_user ON vote_directional (user_id);

CREATE TABLE vote_quality (
  story_id      bigint NOT NULL REFERENCES story (id),
  user_id       bigint NOT NULL REFERENCES app_user (id),
  kind          quality_vote NOT NULL,
  detail        jsonb,
  cast_at       timestamptz NOT NULL DEFAULT now(),
  discounted_at timestamptz,
  PRIMARY KEY (story_id, user_id, kind),
  CHECK (kind <> 'wrong_stock' OR (detail ? 'isin'))           -- PRD-005 §9.2
);
CREATE INDEX vote_quality_reports ON vote_quality (kind, cast_at DESC) WHERE kind IN ('duplicate', 'wrong_stock', 'spam');

-- Counts exclude discounted votes (PRD-005 US-005.6 AC-2) and are kept by trigger.
CREATE TABLE story_vote_count (
  story_id  bigint PRIMARY KEY REFERENCES story (id),
  bullish   integer NOT NULL DEFAULT 0 CHECK (bullish >= 0),
  bearish   integer NOT NULL DEFAULT 0 CHECK (bearish >= 0),
  neutral   integer NOT NULL DEFAULT 0 CHECK (neutral >= 0),
  important integer NOT NULL DEFAULT 0 CHECK (important >= 0)
);

CREATE FUNCTION refresh_story_vote_count(p_story bigint) RETURNS void
LANGUAGE sql AS $$
  INSERT INTO story_vote_count (story_id, bullish, bearish, neutral, important)
  SELECT p_story,
    (SELECT count(*) FROM vote_directional WHERE story_id = p_story AND direction = 'bullish' AND discounted_at IS NULL),
    (SELECT count(*) FROM vote_directional WHERE story_id = p_story AND direction = 'bearish' AND discounted_at IS NULL),
    (SELECT count(*) FROM vote_directional WHERE story_id = p_story AND direction = 'neutral' AND discounted_at IS NULL),
    (SELECT count(*) FROM vote_quality     WHERE story_id = p_story AND kind = 'important'   AND discounted_at IS NULL)
  ON CONFLICT (story_id) DO UPDATE
    SET bullish = EXCLUDED.bullish, bearish = EXCLUDED.bearish,
        neutral = EXCLUDED.neutral, important = EXCLUDED.important
$$;

CREATE FUNCTION vote_changed() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM refresh_story_vote_count(NEW.story_id);
  ELSIF TG_OP = 'DELETE' THEN
    PERFORM refresh_story_vote_count(OLD.story_id);
  ELSE
    PERFORM refresh_story_vote_count(NEW.story_id);
    IF OLD.story_id <> NEW.story_id THEN
      PERFORM refresh_story_vote_count(OLD.story_id);
    END IF;
  END IF;
  RETURN NULL;
END $$;
CREATE TRIGGER vote_directional_count AFTER INSERT OR UPDATE OR DELETE ON vote_directional
  FOR EACH ROW EXECUTE FUNCTION vote_changed();
CREATE TRIGGER vote_quality_count AFTER INSERT OR UPDATE OR DELETE ON vote_quality
  FOR EACH ROW EXECUTE FUNCTION vote_changed();

-- =====================================================================
-- §12  Comments, reports, grievances — PRD-006, D-017, D-022
-- =====================================================================

CREATE TABLE comment (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id      text NOT NULL UNIQUE CHECK (is_public_id(public_id, 'cm')),
  story_id       bigint NOT NULL REFERENCES story (id),
  user_id        bigint NOT NULL REFERENCES app_user (id),
  parent_id      bigint,
  depth          smallint NOT NULL CHECK (depth BETWEEN 1 AND 3),           -- PRD-006 US-006.2 AC-1
  body           text,
  state          comment_state NOT NULL DEFAULT 'visible',
  removed_reason removal_reason,
  created_at     timestamptz NOT NULL DEFAULT now(),
  edited_at      timestamptz,
  UNIQUE (id, story_id),
  -- a reply lives on its parent's story, and moves with it on a story merge
  FOREIGN KEY (parent_id, story_id) REFERENCES comment (id, story_id) ON UPDATE CASCADE,
  CHECK ((parent_id IS NULL) = (depth = 1)),
  CHECK (state <> 'visible' OR (body IS NOT NULL AND char_length(body) BETWEEN 1 AND 2000)),  -- AC-3
  CHECK (state = 'visible' OR body IS NULL),
  CHECK ((state = 'removed') = (removed_reason IS NOT NULL))
);
CREATE INDEX comment_story ON comment (story_id, created_at);
CREATE INDEX comment_profile ON comment (user_id, created_at DESC) WHERE state = 'visible';
CREATE INDEX comment_replies ON comment (parent_id, created_at) WHERE parent_id IS NOT NULL;

-- Depth from parent; a reply to a level-3 comment is placed at level 3 (PRD-006 US-006.2 AC-1).
CREATE FUNCTION comment_set_depth() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE p record;
BEGIN
  IF NEW.parent_id IS NULL THEN
    NEW.depth := 1;
  ELSE
    SELECT id, parent_id, depth INTO p FROM comment WHERE id = NEW.parent_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'parent comment % not found', NEW.parent_id; END IF;
    IF p.depth >= 3 THEN
      NEW.parent_id := p.parent_id;
      NEW.depth := 3;
    ELSE
      NEW.depth := p.depth + 1;
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER comment_set_depth BEFORE INSERT ON comment
  FOR EACH ROW EXECUTE FUNCTION comment_set_depth();

CREATE TABLE comment_revision (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  comment_id bigint NOT NULL REFERENCES comment (id),
  body       text NOT NULL,
  revised_at timestamptz NOT NULL DEFAULT now(),
  purge_after timestamptz
);
CREATE INDEX comment_revision_purge ON comment_revision (purge_after) WHERE purge_after IS NOT NULL;

-- Removed content kept 180 days, then purged (PRD-006 US-006.8 AC-6).
CREATE TABLE removed_content (
  comment_id  bigint PRIMARY KEY REFERENCES comment (id),
  body        text NOT NULL,
  removed_at  timestamptz NOT NULL DEFAULT now(),
  purge_after timestamptz NOT NULL,
  CHECK (purge_after > removed_at)
);
CREATE INDEX removed_content_purge ON removed_content (purge_after);

CREATE TABLE comment_report (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  reference   text NOT NULL UNIQUE CHECK (reference ~ '^GR-[0-9]{4}-[0-9]{6}$'),
  comment_id  bigint NOT NULL REFERENCES comment (id),
  reporter_id bigint NOT NULL REFERENCES app_user (id),
  reason      report_reason NOT NULL,
  detail      text CHECK (char_length(detail) <= 2000),
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (comment_id, reporter_id)
);

CREATE TABLE grievance (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  reference          text NOT NULL UNIQUE CHECK (reference ~ '^GR-[0-9]{4}-[0-9]{6}$'),
  source             grievance_source NOT NULL,
  urgent             boolean NOT NULL DEFAULT false,         -- PRD-006 US-006.8 AC-3
  comment_id         bigint REFERENCES comment (id),
  complainant_email  citext,
  details            text,
  received_at        timestamptz NOT NULL DEFAULT now(),
  ack_due_at         timestamptz NOT NULL,
  resolve_due_at     timestamptz NOT NULL,
  acknowledged_at    timestamptz,
  resolved_at        timestamptz,
  status             grievance_status NOT NULL DEFAULT 'open',
  decision           text
);
CREATE INDEX grievance_queue ON grievance (status, resolve_due_at) WHERE status IN ('open', 'acknowledged');

-- Deadlines (PRD-006 US-006.8 AC-2…AC-4) — `[INFERRED]` from IT Rules 2021.
CREATE FUNCTION grievance_deadlines() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.ack_due_at := NEW.received_at + interval '24 hours';
  NEW.resolve_due_at := CASE
    WHEN NEW.source IN ('court_order', 'government_notice') THEN NEW.received_at + interval '36 hours'
    WHEN NEW.urgent THEN NEW.received_at + interval '24 hours'
    ELSE NEW.received_at + interval '15 days'
  END;
  RETURN NEW;
END $$;
CREATE TRIGGER grievance_deadlines BEFORE INSERT ON grievance
  FOR EACH ROW EXECUTE FUNCTION grievance_deadlines();

CREATE TABLE takedown (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  comment_id   bigint NOT NULL REFERENCES comment (id),
  grievance_id bigint REFERENCES grievance (id),
  reason       removal_reason NOT NULL,
  operator_id  bigint NOT NULL REFERENCES app_user (id),
  reference    text,
  taken_at     timestamptz NOT NULL DEFAULT now(),
  disputed_at  timestamptz,
  dispute_outcome text CHECK (dispute_outcome IN ('upheld', 'reversed')),
  -- legal orders must cite a grievance; spam removal (D-022) needs none
  CHECK (reason NOT IN ('court_order', 'government_notice') OR grievance_id IS NOT NULL)
);
CREATE INDEX takedown_comment ON takedown (comment_id);

-- =====================================================================
-- §13  Live events — ADR-004/005 (partitioned daily, 24 h retention)
-- =====================================================================

CREATE TABLE live_event (
  id         bigint GENERATED ALWAYS AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  type       text NOT NULL CHECK (type IN ('story.created', 'story.updated', 'session.changed', 'source.health')),
  payload    jsonb NOT NULL,
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- =====================================================================
-- §14  Audit — GUARDRAILS §4.8 (append-only, partitioned monthly)
-- No direct personal identifiers in audit rows: actors are internal IDs;
-- IP addresses live in ip_log, which is dropped after 180 days (PRD-005 OQ-005.6).
-- =====================================================================

CREATE TABLE audit_log (
  id          bigint GENERATED ALWAYS AS IDENTITY,
  at          timestamptz NOT NULL DEFAULT now(),
  actor_type  actor_type NOT NULL,
  actor_id    bigint,
  action      text NOT NULL CHECK (action ~ '^[a-z][a-z0-9_.]*$'),
  entity_type text NOT NULL,
  entity_id   text NOT NULL,
  before      jsonb,
  after       jsonb,
  PRIMARY KEY (id, at),
  CHECK (actor_type = 'system' OR actor_id IS NOT NULL)
) PARTITION BY RANGE (at);
CREATE INDEX audit_log_entity ON audit_log (entity_type, entity_id, at DESC);

CREATE FUNCTION audit_log_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'GUARDRAILS 4.8: audit_log is append-only';
END $$;
CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();

CREATE TABLE ip_log (
  audit_id bigint NOT NULL,
  at       timestamptz NOT NULL,
  ip       inet NOT NULL,
  PRIMARY KEY (audit_id, at)
) PARTITION BY RANGE (at);

-- =====================================================================
-- §15  Partition maintenance — partitioning.md
-- =====================================================================

CREATE FUNCTION ensure_monthly_partitions(p_parent regclass, p_months_ahead integer) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
  v_month date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
  v_from  date;
  v_to    date;
  i       integer;
BEGIN
  FOR i IN 0..p_months_ahead LOOP
    v_from := (v_month + make_interval(months => i))::date;
    v_to   := (v_month + make_interval(months => i + 1))::date;
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I PARTITION OF %s FOR VALUES FROM (%L) TO (%L)',
                   p_parent::text || '_' || to_char(v_from, 'YYYYMM'), p_parent,
                   v_from::timestamp AT TIME ZONE 'UTC', v_to::timestamp AT TIME ZONE 'UTC');
  END LOOP;
END $$;

CREATE FUNCTION ensure_daily_partitions(p_parent regclass, p_days_ahead integer) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
  v_day date := (now() AT TIME ZONE 'UTC')::date;
  v_from date;
  i integer;
BEGIN
  FOR i IN 0..p_days_ahead LOOP
    v_from := v_day + i;
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I PARTITION OF %s FOR VALUES FROM (%L) TO (%L)',
                   p_parent::text || '_' || to_char(v_from, 'YYYYMMDD'), p_parent,
                   v_from::timestamp AT TIME ZONE 'UTC', (v_from + 1)::timestamp AT TIME ZONE 'UTC');
  END LOOP;
END $$;

-- Safety nets: inserts never fail for a missing partition; the scheduler alerts if a default has rows.
CREATE TABLE audit_log_default  PARTITION OF audit_log  DEFAULT;
CREATE TABLE ip_log_default     PARTITION OF ip_log     DEFAULT;
CREATE TABLE ai_call_default    PARTITION OF ai_call    DEFAULT;
CREATE TABLE live_event_default PARTITION OF live_event DEFAULT;

SELECT ensure_monthly_partitions('audit_log', 3);
SELECT ensure_monthly_partitions('ip_log', 3);
SELECT ensure_monthly_partitions('ai_call', 3);
SELECT ensure_daily_partitions('live_event', 3);

-- =====================================================================
-- §16  Read views
-- =====================================================================

-- PRD-002 C-002.3: model tags below the display threshold are never shown.
CREATE VIEW story_tag_display AS
SELECT st.story_id, st.isin, st.method, st.confidence
FROM story_tag st
WHERE st.method <> 'model'
   OR st.confidence >= (SELECT (value #>> '{}')::numeric FROM setting WHERE key = 'tag_display_threshold');

-- Paid while a trial or a not-yet-ended subscription period is running (PRD-007 US-007.8 AC-2).
CREATE VIEW user_tier AS
SELECT u.id AS user_id,
       CASE WHEN EXISTS (SELECT 1 FROM subscription s
                         WHERE s.user_id = u.id AND s.status <> 'expired' AND s.current_period_end > now())
              OR EXISTS (SELECT 1 FROM trial t WHERE t.user_id = u.id AND t.ends_at > now())
            THEN 'paid'::tier ELSE 'free'::tier END AS tier
FROM app_user u;

CREATE VIEW ai_spend_month AS
SELECT date_trunc('month', called_at AT TIME ZONE 'Asia/Kolkata') AS month_ist,
       sum(cost_inr) AS cost_inr,
       count(*)      AS calls
FROM ai_call
GROUP BY 1;

-- =====================================================================
-- §17  Seed data
-- =====================================================================

INSERT INTO event_type (code, label, alert_default, taxonomy_version) VALUES
  ('results',             'Results',                 true,  1),
  ('board_outcome',       'Board outcome',           true,  1),
  ('board_intimation',    'Board meeting date',      false, 1),
  ('dividend',            'Dividend',                true,  1),
  ('corporate_action',    'Corporate action',        true,  1),
  ('fundraise',           'Fundraise',               true,  1),
  ('ma',                  'M&A',                     true,  1),
  ('order_contract',      'Order / contract',        true,  1),
  ('pledge',              'Pledge',                  true,  1),
  ('insider_sast',        'Insider / SAST',          true,  1),
  ('rating',              'Rating',                  true,  1),
  ('mgmt_change',         'Management change',       true,  1),
  ('regulatory',          'Regulatory',              true,  1),
  ('litigation',          'Litigation',              true,  1),
  ('investor_comms',      'Investor communication',  false, 1),
  ('shareholder_meeting', 'Shareholder meeting',     false, 1),
  ('trading_window',      'Trading window',          false, 1),
  ('routine_compliance',  'Routine compliance',      false, 1),
  ('macro',               'Market-wide',             false, 1),
  ('other',               'Other',                   false, 1);

INSERT INTO plan_entitlement VALUES
  ('free', 20,  5,  5, 30,   30,  false, false, 0),          -- PRD-007 §2.1 (history 30 days, D-023)
  ('paid', 200, 30, 10, NULL, 365, true,  true,  10);

INSERT INTO setting (key, value) VALUES
  ('tag_display_threshold',       '0.95'),                    -- PRD-002 OQ-002.3
  ('directional_voting_enabled',  'true'),                    -- PRD-005 US-005.7
  ('comments_posting_enabled',    'true'),                    -- PRD-006 US-006.6
  ('comments_visible',            'true'),
  ('ai_model',                    '"claude-haiku-4-5"'),      -- D-025
  ('ai_monthly_cap_inr',          '50000'),                   -- D-025
  ('cluster_merge_threshold',     '0.75'),                    -- deduplication.md §4
  ('cluster_attach_threshold',    '0.6');

INSERT INTO reserved_username (name) VALUES
  ('stockpanic'), ('admin'), ('administrator'), ('operator'), ('support'), ('help'),
  ('grievance'), ('official'), ('moderator'), ('system'), ('root'),
  ('sebi'), ('rbi'), ('nse'), ('bse'), ('nseindia'), ('bseindia'), ('mca'), ('cdsl'), ('nsdl');

-- =====================================================================
-- §18  Roles and grants — schema.md §6
-- =====================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'stockpanic_app') THEN
    CREATE ROLE stockpanic_app NOLOGIN;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO stockpanic_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO stockpanic_app;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO stockpanic_app;

-- Append-only and reference tables
REVOKE UPDATE, DELETE, TRUNCATE ON audit_log, ip_log FROM stockpanic_app;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON event_type, plan_entitlement, reserved_username, schema_migrations
  FROM stockpanic_app;

-- Partitions are reached only through their parent; no direct grants on any partition.
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT c.oid::regclass AS part
           FROM pg_inherits i JOIN pg_class c ON c.oid = i.inhrelid
           WHERE c.relkind IN ('r', 'p')
  LOOP
    EXECUTE format('REVOKE ALL ON %s FROM stockpanic_app', r.part);
  END LOOP;
END $$;

INSERT INTO schema_migrations (version) VALUES ('0001_initial');

COMMIT;
